service: product-service

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  profile: personalAccount
  region: eu-west-1
  stage: dev

functions:
  getProductsList:
    handler: dist/handlers/getProductsList.getProductsList
    events:
      - http:
          path: /products
          method: GET

  getProductsById:
    handler: dist/handlers/getProductsById.getProductsById
    events:
      - http:
          path: /products/{id}
          method: GET
