service: cart-service

frameworkVersion: "3"

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs18.x
  profile: personalAccount
  region: eu-west-1
  stage: dev

functions:
  main:
    handler: dist/cartHandler.handler
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: '{proxy+}'
          cors: true
