service: import-service

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: personalAccount
  region: eu-west-1
  stage: dev
  iam:
    role: ImportServiceRole
  environment:
    BUCKET_MANE: sp-import-service-bucket
    REGION: eu-west-1

custom:
  bucketName: sp-import-service-bucket

package:
  individually: true
  exclude:
    - ./**

functions:
  importProductsFile:
    handler: dist/handlers/importProductsFile.importProductsFile
    package:
      include:
        - dist/handlers/importProductsFile.js
    events:
      - http:
          path: /import
          method: GET
          request:
            parameters:
              querystrings:
                name: true

  importFileParser:
    handler: dist/handlers/importFileParser.importFileParser
    package:
      include:
        - dist/handlers/importFileParser.js
    events:
     - s3:
        bucket: ${self:custom.bucketName}
        event: s3:ObjectCreated:*
        rules:
          - prefix: uploaded/
          - suffix: .csv
        existing: true

resources:
  Resources:
    ImportServiceRole:
        Type: AWS::IAM::Role
        Properties:
          RoleName: ImportServiceLambdaS3Access
          AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Principal:
                  Service:
                    - lambda.amazonaws.com
                Action: sts:AssumeRole
          ManagedPolicyArns:
            - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
          Policies:
            - PolicyName: ImportServiceAccessPolicy
              PolicyDocument:
                Version: "2012-10-17"
                Statement:
                  - Effect: Allow
                    Action:
                    - s3:PutObject
                    - s3:PutObjectAcl
                    - s3:GetObject
                    - s3:DeleteObject
                    Resource:
                      - arn:aws:s3:::${self:custom.bucketName}/*
